[FuseConsumerIntoLoop] Add support for fusing iteratively
nod-ai/iree-amd-aie pull request #1003
Opened 2024-12-31 14:52 UTC by jtuyls

This PR adds support for iterative consumer fusion until no fusion opportunity can be found. See the test for an example in which this is needed: https://github.com/nod-ai/iree-amd-aie/compare/main...jtuyls:fuse-consumer-iters?expand=1#diff-df15abde86fbca464fa0a1e81b81bab2faaae00ea6a0aae73a9ba57477d78b05R471

2025-01-01 07:03 UTC, Abhishek-Varma requested changes
Nice! I have one proposal and one test related comment.

2025-01-02 10:13 UTC, jtuyls commented on compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEFuseConsumerIntoLoop.cpp
> +    for (unsigned depth = 1; depth <= fuseDepth; depth++) {
The purpose of `fuseDepth` is different from `maxIterations`, for example:
```
scf.forall {
  scf.forall {
    computeOp
  }
}
unpackOp
unpackOp
```

`fuseDepth == 1` would just focus on the first `unpackOp` and try to fuse it as close as possible to the `computeOp`, while setting `fuseDepth == 2` would try to fuse both unpack ops and therefore `fuseDepth` and `maxIterations` are orthogonal and can be combined.

2025-01-02 10:39 UTC, jtuyls commented on compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/fuse_consumer_into_loop.mlir
> +  %0 = hal.interface.binding.subspan layout(<bindings = [#hal.pipeline.binding<storage_buffer, "ReadOnly|Indirect">, #hal.pipeline.binding<storage_buffer, "ReadOnly|Indirect">, #hal.pipeline.binding<
Done

2025-01-02 11:04 UTC, Abhishek-Varma commented on compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEFuseConsumerIntoLoop.cpp
> +    for (unsigned depth = 1; depth <= fuseDepth; depth++) {
Yes, I understand the purpose is different - but `fuseDepth` is actually just a hack that has been carried over.
Since we're now trying to make this pass greedily fuse/fuse iteratively - it'd be nice to get rid of the hack as part of the same.

Basically I'm trying to suggest that the concept of greedily fusing is applied throughout this pass' design at the following two places :-

1. Which loop-like level to fuse into -> `maxIteration` : this is good which this pass adds.
2. How many consumers to fuse at a particular loop-like level -> `fuseDepth` :  currently hardcoded based on dispatch and as a design point-of-view this seems like an ugly hack to keep now that we are trying to add the former.

I believe the last unpack would anyway not get fused if we tried -> the upstream consumer fusion API would fail because the `inner_tile` is not equal to the producer tile size.
```
%unpack = tensor.unpack %15 outer_dims_perm = [0, 1, 3, 2] inner_dims_pos = [2, 3] inner_tiles = [8, 8] into %7 : tensor<2x2x4x4x8x8xf32> -> tensor<2x2x32x32xf32>
%unpack_11 = tensor.unpack %unpack inner_dims_pos = [0, 1] inner_tiles = [32, 32] into %arg2 : tensor<2x2x32x32xf32> -> tensor<64x64xf32>

where the producer tile size is `8x8` therefore only %unpack is fusable.
```
And this failure should be a correct signal for how many consumers we can fuse for a particuler loop-like level.

1. `Matmul` : We fuse in just one unpack.
2. `Matmul + Elementwise` : We do what we do for pure Matmul, and add elementwise to the list.

Design-wise, I'd advocate that if the last unpack is indeed not-fusable, we get rid of `fuseDepth` and let the fusion at a particular loop-like level also take place greedily/iteratively - it seems like a better design overall instead of hardcoding based on the type of dispatch (unless there is a very good reason to always keep the type of dispatch in this decision making).

And since `maxIteration` has been set to quite a high number `100` anyway, we can indeed make use of that.

2025-01-02 11:33 UTC, jtuyls commented on compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEFuseConsumerIntoLoop.cpp
> +    for (unsigned depth = 1; depth <= fuseDepth; depth++) {
> Yes, I understand the purpose is different - but fuseDepth is actually just a hack that has been carried over.
Since we're now trying to make this pass greedily fuse/fuse iteratively - it'd be nice to get rid of the hack as part of the same.

I agree that `fuseDepth` is hacky but I think it's unrelated and to this PR and orthogonal to `maxIterations`. This PR doesn't affect and change anything about `fuseDepth` and is just an incremental change on top of the existing logic that I need for adding an additional level of tiling. Additionally, removing `fusingDepth`/trying to fuse the outer unpack leads to errors with an additional level of tiling that need to be resolved first and as this might be a larger change/refactoring I would like to leave that for future work.

2025-01-02 12:02 UTC, Abhishek-Varma approved these changes
LGTM!

2025-01-02 12:18 UTC, merged