bump IREE, mlir-aie and mlir-air
nod-ai/iree-amd-aie pull request #108
Opened 2024-01-26 22:31 UTC by nirvedhmeshram

make required changes to tile and fuse to match upstream.

There are some bufferization issues that are causing failure in the C++ pass way of running e2e. Currently working on resolving that.

2024-01-28 23:28 UTC, MaheshRavishankar requested changes
Left a few comments. I'll take a shot at addressing these.

2024-01-28 23:28 UTC, MaheshRavishankar commented on compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIETileAndFuse.cpp
> +  if (!useSCFFor) {
This can just be set in the caller, and you can just pass the options object by `const &`

2024-01-28 23:28 UTC, MaheshRavishankar commented on compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIETileAndFuse.cpp
> +    tileAndFuseOptions.setFusionControlFn(
This is same as above. Is this what you wanted to do?

2024-01-28 23:28 UTC, MaheshRavishankar commented on compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIETileAndFuse.cpp
> +  else {
There might be a better check here. We just need to make sure that if we are using tiling a reduction dimension, then we don't fuse.

2024-01-28 23:28 UTC, MaheshRavishankar commented on compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.td
> +    Option<"useFusion", "use-fusion", "bool", /*default=*/"true",
Maybe we can do that as a follow up, but we want to use fusion all the time on this hardware. We just need to be careful about the tile sizes used.

2024-01-29 08:02 UTC, Abhishek-Varma commented
Besides the other comments, I have added a utility function `isTilingReductionDimension` and am switching the `FusionControlFn` based on the same.

I couldn't find any specific test case that made use of the `use-fusion` flag though and saw that even without the utility function `isTilingReductionDimension` + the FusionControlFn switching, all the lit tests were surprisingly passing - not sure if there's an error in my observation.

I therefore manually tested [tile_and_fuse_using_scf_for.mlir](https://github.com/nod-ai/iree-amd-aie/blob/main/compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/tile_and_fuse_using_scf_for.mlir) and [tile_and_fuse_using_scf_forall.mlir](https://github.com/nod-ai/iree-amd-aie/blob/main/compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/tile_and_fuse_using_scf_forall.mlir) to confirm whether the utility function I added works nonetheless - "DO NOT fuse if tiling is occurring at _any_ of the reduction dimension" (just added a debug statement to doubly confirm, besides the still passing lit tests).

@MaheshRavishankar @nirvedhmeshram you may review and let me know if the recent commit changes looks good.

2024-01-29 17:20 UTC, MaheshRavishankar approved these changes
Nice! Thanks!

2024-01-29 17:25 UTC, MaheshRavishankar commented
cc @yzhang93 do you want to look at this to make sure you have a path for the fill fusion with peeling... You should be able to use upstream methods.

2024-01-29 19:09 UTC, yzhang93 commented
> With the upstream tile and fuse utilities, we can customize what kind of tiling (scf.for/sc.for_all) and fusion we want. I have added a new option to control fusion which is working well for the pad stuff. @yzhang93 since now you can fuse fill in scf.for I have removed the pass you added. Please let me know if I am missing some case for which you needed that pass.

@nirvedhmeshram I don't think we should fuse fill op into the reduction loops. In that case we'll still need to use `FuseFillIntoForall` pass after the for loop is peeled for fusion. Just need to refactor the codes in that pass to call the upstream methods directly.

2024-01-29 19:13 UTC, yzhang93 requested changes
Thanks for bumping the latest libraries. Just need to add `FuseFillIntoForall` pass back, the others LGTM.

2024-01-29 23:30 UTC, yzhang93 commented
There is another case that I think needs the `FuseFillIntoForall` pass. 

```
// -----// IR Dump After AMDAIEBufferizeToAllocation (iree-amdaie-bufferize-to-allocation) //----- //
func.func @matmul_static_dispatch_0_matmul_8x8x16_i32() {
  %c0 = arith.constant 0 : index
  %c0_i32 = arith.constant 0 : i32
  %0 = hal.interface.binding.subspan set(0) binding(0) type(storage_buffer) alignment(64) offset(%c0) flags(ReadOnly) : !flow.dispatch.tensor<readonly:tensor<8x16xi32>>
  %1 = hal.interface.binding.subspan set(0) binding(1) type(storage_buffer) alignment(64) offset(%c0) flags(ReadOnly) : !flow.dispatch.tensor<readonly:tensor<16x32xi32>>
  %2 = hal.interface.binding.subspan set(0) binding(2) type(storage_buffer) alignment(64) offset(%c0) : !flow.dispatch.tensor<writeonly:tensor<8x32xi32>>
  %3 = flow.dispatch.tensor.load %0, offsets = [0, 0], sizes = [8, 16], strides = [1, 1] : !flow.dispatch.tensor<readonly:tensor<8x16xi32>> -> tensor<8x16xi32>
  %4 = flow.dispatch.tensor.load %1, offsets = [0, 0], sizes = [16, 32], strides = [1, 1] : !flow.dispatch.tensor<readonly:tensor<16x32xi32>> -> tensor<16x32xi32>
  %5 = tensor.empty() : tensor<8x32xi32>
  %6 = scf.forall (%arg0, %arg1) = (0, 0) to (8, 32) step (8, 16) shared_outs(%arg2 = %5) -> (tensor<8x32xi32>) {
    %extracted_slice = tensor.extract_slice %3[%arg0, 0] [8, 16] [1, 1] : tensor<8x16xi32> to tensor<8x16xi32>
    %extracted_slice_0 = tensor.extract_slice %4[0, %arg1] [16, 16] [1, 1] : tensor<16x32xi32> to tensor<16x16xi32>
    %extracted_slice_1 = tensor.extract_slice %arg2[%arg0, %arg1] [8, 16] [1, 1] : tensor<8x32xi32> to tensor<8x16xi32>
    %7 = linalg.fill ins(%c0_i32 : i32) outs(%extracted_slice_1 : tensor<8x16xi32>) -> tensor<8x16xi32>
    %8 = tensor.empty() : tensor<1x1x16x64xi32>
    %c0_i32_2 = arith.constant 0 : i32
    %alloc = memref.alloc() : memref<1x1x16x64xi32, 1 : i32>
    %9 = bufferization.to_tensor %alloc restrict writable : memref<1x1x16x64xi32, 1 : i32>
    %pack = tensor.pack %extracted_slice padding_value(%c0_i32_2 : i32) inner_dims_pos = [0, 1] inner_tiles = [16, 64] into %9 : tensor<8x16xi32> -> tensor<1x1x16x64xi32>
    %10 = tensor.empty() : tensor<1x1x64x64xi32>
    %c0_i32_3 = arith.constant 0 : i32
    %11 = tensor.empty() : tensor<1x1x64x64xi32>
    %alloc_4 = memref.alloc() : memref<1x1x64x64xi32, 1 : i32>
    %12 = bufferization.to_tensor %alloc_4 restrict writable : memref<1x1x64x64xi32, 1 : i32>
    %pack_5 = tensor.pack %extracted_slice_0 padding_value(%c0_i32_3 : i32) outer_dims_perm = [0, 1] inner_dims_pos = [0, 1] inner_tiles = [64, 64] into %12 : tensor<16x16xi32> -> tensor<1x1x64x64xi32>
    %13 = tensor.empty() : tensor<1x1x16x64xi32>
    %c0_i32_6 = arith.constant 0 : i32
    %alloc_7 = memref.alloc() : memref<1x1x16x64xi32, 1 : i32>
    %14 = bufferization.to_tensor %alloc_7 restrict writable : memref<1x1x16x64xi32, 1 : i32>
    %pack_8 = tensor.pack %7 padding_value(%c0_i32_6 : i32) inner_dims_pos = [0, 1] inner_tiles = [16, 64] into %14 : tensor<8x16xi32> -> tensor<1x1x16x64xi32>
    %15 = linalg.generic {indexing_maps = [affine_map<(d0, d1, d2, d3, d4, d5) -> (d0, d2, d3, d5)>, affine_map<(d0, d1, d2, d3, d4, d5) -> (d2, d1, d5, d4)>, affine_map<(d0, d1, d2, d3, d4, d5) -> (d0, d1, d3, d4)>], iterator_types = ["parallel", "parallel", "reduction", "parallel", "parallel", "reduction"]} ins(%pack, %pack_5 : tensor<1x1x16x64xi32>, tensor<1x1x64x64xi32>) outs(%pack_8 : tensor<1x1x16x64xi32>) {
    ^bb0(%in: i32, %in_9: i32, %out: i32):
      %16 = arith.muli %in, %in_9 : i32
      %17 = arith.addi %out, %16 : i32
      linalg.yield %17 : i32
    } -> tensor<1x1x16x64xi32>
    %unpack = tensor.unpack %15 inner_dims_pos = [0, 1] inner_tiles = [16, 64] into %7 : tensor<1x1x16x64xi32> -> tensor<8x16xi32>
    memref.dealloc %alloc : memref<1x1x16x64xi32, 1 : i32>
    memref.dealloc %alloc_4 : memref<1x1x64x64xi32, 1 : i32>
    memref.dealloc %alloc_7 : memref<1x1x16x64xi32, 1 : i32>
    scf.forall.in_parallel {
      tensor.parallel_insert_slice %unpack into %arg2[%arg0, %arg1] [8, 16] [1, 1] : tensor<8x16xi32> into tensor<8x32xi32>
    }
  } {mapping = [#gpu.block<y>, #gpu.block<x>]}
  flow.dispatch.tensor.store %6, %2, offsets = [0, 0], sizes = [8, 32], strides = [1, 1] : tensor<8x32xi32> -> !flow.dispatch.tensor<writeonly:tensor<8x32xi32>>
  return
}
```

In this case, we don't want to fuse tensor.pack in the forall loops, so it stops propagating its producer `linalg.fill` fusing into the forall loop. I believe this causes the failure of the e2e test @Abhishek-Varma and I put together.

```
// -----// IR Dump After AMDAIETileAndFuse (iree-amdaie-tile-and-fuse) //----- //
func.func @matmul_static_dispatch_0_matmul_8x8x16_i32() {
  %c0 = arith.constant 0 : index
  %c0_i32 = arith.constant 0 : i32
  %0 = hal.interface.binding.subspan set(0) binding(0) type(storage_buffer) alignment(64) offset(%c0) flags(ReadOnly) : !flow.dispatch.tensor<readonly:tensor<8x16xi32>>
  %1 = hal.interface.binding.subspan set(0) binding(1) type(storage_buffer) alignment(64) offset(%c0) flags(ReadOnly) : !flow.dispatch.tensor<readonly:tensor<16x32xi32>>
  %2 = hal.interface.binding.subspan set(0) binding(2) type(storage_buffer) alignment(64) offset(%c0) : !flow.dispatch.tensor<writeonly:tensor<8x32xi32>>
  %3 = flow.dispatch.tensor.load %0, offsets = [0, 0], sizes = [8, 16], strides = [1, 1] : !flow.dispatch.tensor<readonly:tensor<8x16xi32>> -> tensor<8x16xi32>
  %4 = flow.dispatch.tensor.load %1, offsets = [0, 0], sizes = [16, 32], strides = [1, 1] : !flow.dispatch.tensor<readonly:tensor<16x32xi32>> -> tensor<16x32xi32>
  %5 = tensor.empty() : tensor<8x32xi32>
  %6 = scf.forall (%arg0, %arg1) = (0, 0) to (8, 32) step (8, 16) shared_outs(%arg2 = %5) -> (tensor<8x32xi32>) {
    %extracted_slice = tensor.extract_slice %3[%arg0, 0] [8, 16] [1, 1] : tensor<8x16xi32> to tensor<8x16xi32>
    %extracted_slice_0 = tensor.extract_slice %4[0, %arg1] [16, 16] [1, 1] : tensor<16x32xi32> to tensor<16x16xi32>
    %extracted_slice_1 = tensor.extract_slice %arg2[%arg0, %arg1] [8, 16] [1, 1] : tensor<8x32xi32> to tensor<8x16xi32>
    %7 = linalg.fill ins(%c0_i32 : i32) outs(%extracted_slice_1 : tensor<8x16xi32>) -> tensor<8x16xi32>
    %8 = tensor.empty() : tensor<1x1x16x64xi32>
    %c0_i32_2 = arith.constant 0 : i32
    %alloc = memref.alloc() : memref<1x1x16x64xi32, 1 : i32>
    %9 = bufferization.to_tensor %alloc restrict writable : memref<1x1x16x64xi32, 1 : i32>
    %pack = tensor.pack %extracted_slice padding_value(%c0_i32_2 : i32) inner_dims_pos = [0, 1] inner_tiles = [16, 64] into %9 : tensor<8x16xi32> -> tensor<1x1x16x64xi32>
    %10 = tensor.empty() : tensor<1x1x64x64xi32>
    %c0_i32_3 = arith.constant 0 : i32
    %11 = tensor.empty() : tensor<1x1x64x64xi32>
    %alloc_4 = memref.alloc() : memref<1x1x64x64xi32, 1 : i32>
    %12 = bufferization.to_tensor %alloc_4 restrict writable : memref<1x1x64x64xi32, 1 : i32>
    %pack_5 = tensor.pack %extracted_slice_0 padding_value(%c0_i32_3 : i32) outer_dims_perm = [0, 1] inner_dims_pos = [0, 1] inner_tiles = [64, 64] into %12 : tensor<16x16xi32> -> tensor<1x1x64x64xi32>
    %13 = tensor.empty() : tensor<1x1x16x64xi32>
    %c0_i32_6 = arith.constant 0 : i32
    %alloc_7 = memref.alloc() : memref<1x1x16x64xi32, 1 : i32>
    %14 = bufferization.to_tensor %alloc_7 restrict writable : memref<1x1x16x64xi32, 1 : i32>
    %pack_8 = tensor.pack %7 padding_value(%c0_i32_6 : i32) inner_dims_pos = [0, 1] inner_tiles = [16, 64] into %14 : tensor<8x16xi32> -> tensor<1x1x16x64xi32>
    %15 = linalg.generic {indexing_maps = [affine_map<(d0, d1, d2, d3, d4, d5) -> (d0, d2, d3, d5)>, affine_map<(d0, d1, d2, d3, d4, d5) -> (d2, d1, d5, d4)>, affine_map<(d0, d1, d2, d3, d4, d5) -> (d0, d1, d3, d4)>], iterator_types = ["parallel", "parallel", "reduction", "parallel", "parallel", "reduction"]} ins(%pack, %pack_5 : tensor<1x1x16x64xi32>, tensor<1x1x64x64xi32>) outs(%pack_8 : tensor<1x1x16x64xi32>) {
    ^bb0(%in: i32, %in_9: i32, %out: i32):
      %17 = arith.muli % [...]

2024-01-29 23:56 UTC, yzhang93 approved these changes

2024-01-29 23:58 UTC, merged