Add multicore flag
nod-ai/iree-amd-aie pull request #128
Opened 2024-02-05 16:46 UTC by frafranz

The PackPipeline makes only use of one AIE tile so far, by tiling to `(16,64)` at the first tiling operation.

With the new flag `use-multicore` this behaviour can be adapted, namely
- `use-multicore=2`: tile to `(16,128)` and use two AIE tiles
- `use-multicore=4`: tile to `(16,256)` and use four AIE tiles.

By default, a single tile is used. Values different than 1, 2 or 4 result in an error.

**TODO:** 
Currently this flag is ignored within the PadPipeline and SimplePackPipeline, is such a case distinction also desired for these ?

2024-02-05 17:06 UTC, frafranz commented
I am currently ignoring the use-multicore flag except for the PackPipeline. I could also adapt the pad-pipeline for different numbers of cores, but I am unsure about the current usage of cores therein. From the dump after ParallelToHerd, I would interpret that all four cores are used here:

 ```
%c2_8 = arith.constant 2 : index
 %c2_9 = arith.constant 2 : index   
 air.herd @herd_0  tile (%arg2, %arg3) in (%arg4=%c2_8, %arg5=%c2_9) args(%arg6=%alloc_3, %arg7=%alloc, %arg8=%alloc_2) : memref<8x8xi32, 1 : i32>, memref<8x256xi8, 1 : i32>, memref<256x8xi8, 1 : i32> {
    ...
}
```
@yzhang93 are you familiar with this?
If this interpretation is correct, I would set useMulticore=4 by default for this pipeline, and for other values throw an error.

2024-02-05 17:26 UTC, newling commented
Name suggestion: `iree-amd-aie-num-cores`.  Currently the flag name sounds to me like a binary "use or don't use multicore". Do you know if 'cores' or 'tiles' is more commonly used?

2024-02-05 17:27 UTC, frafranz commented
> Name suggestion: `iree-amd-aie-num-cores`. Currently the flag name sounds to me like a binary "use or don't use multicore". Do you know if 'cores' or 'tiles' is more commonly used?

True, I prefer your suggestion. I have heard both in verbal use, but within the AIR dialect I have seen 'tile' so perhaps that is more specific?

2024-02-05 18:45 UTC, yzhang93 commented
> @yzhang93 @MaheshRavishankar Is this interpretation correct? And are you interested in an adaptable number of cores for the Pad and SimplePack pipelines? If so, I would set `iree-amdaie-num-cores=4` by default for this pipeline, and for other values adapt the tiling parameters or throw an error.

Thanks for your contribution. I think currently we should use this flag to pack pipeline only, and we will adapt it to other pipelines later.

2024-02-06 05:51 UTC, MaheshRavishankar requested changes
Actually if you dont mind I have a suggeston that will help us in the future. Introduce a new struct called `AIEConfig` in `KernelDispatch.h` and populate it with just one filed `num_cores`. I expect we can adapt this to capture the configuration better over time, but this would have been plumbed through to begin with.

2024-02-06 07:46 UTC, frafranz commented
> Actually if you dont mind I have a suggeston that will help us in the future. Introduce a new struct called `AIEConfig` in `KernelDispatch.h` and populate it with just one filed `num_cores`. I expect we can adapt this to capture the configuration better over time, but this would have been plumbed through to begin with.

Sure that makes sense, the struct would be right next to the enum for the pass pipeline. I will then have this struct be filled depending on the flag, is that what you mean? Or do you suggest to leave out the flag altogether and only use the value hardcoded in the struct?

Our default values are 1 for the pack pipeline and - as it seemed to me from later dumps - 4 for the pad pipeline.

2024-02-07 15:30 UTC, frafranz commented
I was wondering whether at some point the information on spatial tiling would become part of https://github.com/openxla/iree/blob/8c4c3e03ff4e7797eaf00e2682e63971096fabfd/compiler/src/iree/compiler/Codegen/Dialect/Codegen/IR/IREECodegenAttrs.td#L177 upstream, so that it can be passed together with tile_sizes to the matmul op @yzhang93  @MaheshRavishankar For now however I am fine with leaving the handling like it is here, please let me know if there is anything left to adapt!

2024-02-08 10:55 UTC, frafranz commented on compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEAddLoweringStrategy.cpp
> +  if (failed(initAIELaunchConfig(moduleOp, usePassPipeline, numCores))) {
I have adapted this and rebased.

2024-02-08 21:24 UTC, MaheshRavishankar approved these changes

2024-02-08 21:24 UTC, MaheshRavishankar commented
Thanks!

2024-02-09 11:42 UTC, FranzHaniel commented
I just rebased and ran CI again, if you agree to these changes @yzhang93 I will merge this PR.

2024-02-09 12:10 UTC, merged