Clean up BufferizeToAllocation pass
nod-ai/iree-amd-aie pull request #261
Opened 2024-04-02 20:02 UTC by yzhang93

- Change the bufferizeLevel to a Enum class of BufferizeOperand to make codes more readable.
- Add support to bufferize the operands from defining ops of a matmul, which is needed for the new pack-peel based pipeline.
- Remove the previous tests, and add a single test file to demonstrate all bufferization cases.

2024-04-03 05:34 UTC, Abhishek-Varma requested changes

2024-04-03 05:34 UTC, Abhishek-Varma commented on compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEBufferizeToAllocation.cpp
> +// ops and used for new allocation creation.
nit:

```
// This functions helps to fetch operands of either a LinalgOp or its defining ops,
// based on which operands the caller wants to bufferize via `bufferizeOperand`
// parameter.
```

2024-04-03 05:34 UTC, Abhishek-Varma commented on compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEBufferizeToAllocation.cpp
> +  FailureOr<SmallVector<Value>> operands =
nit: `operand` -> `operandsToBufferize`.

2024-04-03 05:34 UTC, Abhishek-Varma commented on compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEBufferizeToAllocation.cpp
> +static SmallVector<Value> getOperandsFromDefOp(linalg::LinalgOp &linalgOp) {
Add a doc comment for this function.

2024-04-03 05:34 UTC, Abhishek-Varma commented on compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/KernelDispatch.h
> +/// Enum for operands for bufferizing to allocation.
nit: `Enum for operands to be bufferized to allocation.`

2024-04-03 05:34 UTC, Abhishek-Varma commented on compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEBufferizeToAllocation.cpp
> +    case BufferizeOperand::Input:
`Out` -> `Lhs and Rhs`.

2024-04-03 05:34 UTC, Abhishek-Varma commented on compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEBufferizeToAllocation.cpp
> +    case BufferizeOperand::Output:
`Lhs, Rhs` -> `Out`.

2024-04-03 05:34 UTC, Abhishek-Varma commented on compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.td
> +                   "Create new allocations for lhs, rhs of a matmul."),
The enum descriptions for `input` and `output` needs to be interchanged.

2024-04-03 05:34 UTC, Abhishek-Varma commented on compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.td
> +      "Select which operands of a matmul to be bufferized to allocation",
`matmul` -> `linalg op` - since the pass can be applied to literally any ContractionOpInterface LinalgOp.

2024-04-03 16:26 UTC, MaheshRavishankar requested changes

2024-04-03 16:26 UTC, MaheshRavishankar commented on compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEBufferizeToAllocation.cpp
> +  return operands;
Not sure what this is doing?

2024-04-03 20:06 UTC, yzhang93 commented on compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEBufferizeToAllocation.cpp
> +    operands.push_back(input.getDefiningOp()->getOperand(0));
Good points! Thanks for catching this.

2024-04-04 05:48 UTC, Abhishek-Varma reviewed
A few nit comments. Looks good overall!

2024-04-04 05:48 UTC, Abhishek-Varma commented on compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.td
> +      "Select which operands of a matmul to be bufferized to allocation",
I see this wasn't addressed - marking it unresolved.

2024-04-04 05:48 UTC, Abhishek-Varma commented on compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEBufferizeToAllocation.cpp
> +/// Utility to get operands from the defining ops of LinalgOp input operands.
nit: `Utility to fetch operands from the defining ops of LinalgOp's input operands.`.

Also note: the utility is not fetching ALL/INPUT/INIT operands of the defining ops. It's only fetching the first input operand. You may want to include this information as part of the doc comment.

And, thank you for using triple quotes for doc comment - it's a good practice to use triple comments (`///`) for anything outside the function and double comments (`//`) within. I missed that previously, so thank you!
The only exception here is - whenever we are defining `structs` we should use triple comments within it to explain each member variables.

2024-04-04 05:48 UTC, Abhishek-Varma commented on compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEBufferizeToAllocation.cpp
> +    // Create new allocations for Lhs, Rhs and Out.
You may change this to `///` comments following what I wrote in the previous review thread.

2024-04-04 16:05 UTC, MaheshRavishankar approved these changes
Just a few clarifying comments, but looks good. Thanks!

2024-04-04 16:05 UTC, MaheshRavishankar commented on compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.cpp
> +  bufferizeOptions0.bufferizeOperand = BufferizeOperand::InputOutput;
I thought we werent promoting the outputs at this level. Wont this allocate a memory for the output in shared memory?

2024-04-04 17:58 UTC, Abhishek-Varma approved these changes
Approving this since it looks good to me overall and I'd not want to block the merging!
Just few comments to address from the earlier thread.

Thanks @yzhang93 !

2024-04-04 18:57 UTC, merged