Remove legacy pipeline
nod-ai/iree-amd-aie pull request #284
Opened 2024-04-19 19:38 UTC by newling

This PR removes 2 things:

1)  The method `addMLIRAIRAIELegacyLoweringPasses` which is not needed it seems (pad-pack uses 
 the very similar `addMLIRAIRAIELoweringPasses` and pack-peel uses neither (is this an oversight?)). 
 
 2) ` static PassPipelineRegistration<> AIELoweringPipeline("iree-amdaie-aie-lowering-pipeline", ... ` which doesn't seem to be used anywhere. 
 
 Is it ok to just go ahead with these removals, or is a plan to use them in the future?

2024-04-19 20:17 UTC, nirvedhmeshram commented
Not sure if the registration function had some purpose, @MaheshRavishankar ?
Other then that the PR looks good to me. The pad-pack is not using any lowering on purpose as its not plumbed through e2e.

2024-04-19 21:01 UTC, MaheshRavishankar commented
I think this was added for some other out-of-tree users... @yzhang93 has more context. Please wait for her to take a look

2024-04-19 22:03 UTC, yzhang93 requested changes
I think it's fine to remove `MLIRAIRAIELegacyLoweringPasses`, don't remember why it was created in the first place. We should always try to keep a single set of AIRLoweringPasses. Minor change request, otherwise LGTM.

2024-04-19 22:24 UTC, yzhang93 commented
@erwei-xilinx Could you please make sure you are using passes within `MLIRAIRAIELoweringPasses` instead of `MLIRAIRAIELegacyLoweringPasses` when working for pack-peel pipeline? @nirvedhmeshram mentioned there was some problem running `MLIRAIRAIELoweringPasses` on simple-pack pipeline previously.

2024-04-19 22:39 UTC, erwei-xilinx commented
> @erwei-xilinx Could you please make sure you are using passes within `MLIRAIRAIELoweringPasses` instead of `MLIRAIRAIELegacyLoweringPasses` when working for pack-peel pipeline? @nirvedhmeshram mentioned there was some problem running `MLIRAIRAIELoweringPasses` on simple-pack pipeline previously.

@yzhang93 Sure, in my local experiments with pack-peel pipeline, I haven't attempted to change the IREE pipeline, and I think that the default pack-peel pipeline was using `MLIRAIRAIELoweringPasses`.

2024-04-19 23:10 UTC, yzhang93 commented
> > @erwei-xilinx Could you please make sure you are using passes within `MLIRAIRAIELoweringPasses` instead of `MLIRAIRAIELegacyLoweringPasses` when working for pack-peel pipeline? @nirvedhmeshram mentioned there was some problem running `MLIRAIRAIELoweringPasses` on simple-pack pipeline previously.
> 
> @yzhang93 Sure, in my local experiments with pack-peel pipeline, I will be sure to stick to the default `MLIRAIRAIELoweringPasses` pipeline.

Thanks! @newling I would suggest to hold this PR for a while and wait for @erwei-xilinx to make sure `AMDAIEPackToDmaPass()` work for pack-peel pipeline instead of using `AMDAIEDecomposeLinalgExtPackUnPackToAIRPass()`. Then we can safely delete the legacy lowering passes.

2024-04-22 22:40 UTC, yzhang93 commented on compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.cpp
> +  }
You can remove the if condition as well. In the future we should use `addMLIRAIRAIELoweringPasses` for all pipelines.

2024-04-23 16:47 UTC, yzhang93 commented on compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.cpp
> +  }
If you can make this change and rebase on main, then we can merge this PR.

2024-04-26 01:14 UTC, yzhang93 approved these changes
Thanks!

2024-04-26 01:21 UTC, merged