Improve errors and diagnostics in pack-to-dma pass
nod-ai/iree-amd-aie pull request #291
Opened 2024-04-23 16:24 UTC by newling

One of the SD3 matmul failures is due to iree-amd-aie not supporting imperfect tiling of pack operations. They silently fail to lower to air. This PR makes improves the error handling so that it is clearer to diagnose this.

2024-04-23 23:20 UTC, newling commented on compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/pack_to_dma.mlir
> +// RUN: iree-opt --iree-amdaie-pack-to-dma --cse --split-input-file %s | FileCheck %s
It was necessary -- the approach with patterns seems to run it automatically. 

Without cse, duplicate constants are used --  `%c0` and  `%c0_1` both appear as operands of the resulting dma copy. 


I know it's not great having cse/canonicalization in unit tests like this...

2024-04-25 17:45 UTC, nirvedhmeshram requested changes
Looks good, overall, just requesting some minor changes.

2024-04-25 17:45 UTC, nirvedhmeshram commented on compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEPackToDma.cpp
> +LogicalResult processInputs(Operation *op, SmallVector<OpFoldResult> &offsets,
please add a comment explaining the function.

2024-04-25 17:45 UTC, nirvedhmeshram commented on compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEPackToDma.cpp
> +LogicalResult rewriteAsDma(IRRewriter &rewriter, Operation *op, Value input,
here as well. sorry the original pattern should have had a comment too.

2024-04-25 17:45 UTC, nirvedhmeshram commented on compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/test/pack_to_dma.mlir
> +// RUN: iree-opt --iree-amdaie-pack-to-dma --cse --split-input-file %s | FileCheck %s
Lets add canonicalize and cse passes in the pass pipeline where this pass is used so its nice to read when we look at IR.

2024-04-26 01:43 UTC, newling commented
Hi @nirvedhmeshram thanks for the review. I've added 2 comments, and added canonicalization to the pipeline after this pass (which is now needed as before with the pattern-based approach it happened automatically).

2024-04-26 02:53 UTC, nirvedhmeshram commented
curious what the \p in the two comments added is about? Since we are not generating any docs if its a formatting thing, I am not sure if the value add is enough to justify the loss in readability for people directly reading the code?

2024-04-26 02:56 UTC, nirvedhmeshram commented on compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.cpp
> +  passManager.addPass(createCanonicalizerPass());
I would only add these to the else part of the above if/else to not unintentionally mess with the peel-pack flow.

2024-04-26 16:09 UTC, newling commented
> curious what the \p in the two comments added is about? Since we are not generating any docs if its a formatting thing, I am not sure if the value add is enough to justify the loss in readability for people directly reading the code?
> 
> Also wondering what exactly is causing the tests to fail, perhaps some of the dma ops are getting removed by canonicalization as they appear like dead code? This may be why the placement of these passes is so sensitive (not saying it should be of course).

https://www.doxygen.nl/manual/commands.html#cmdp
The use of /// suggests doxygen-style comment so I was being consistent, but can change. 
Hmm yes, probably adding canonicalization to the pass pipeline tripped a lit test. I didn't run the tests locally. Will investigate asap.

2024-04-26 16:26 UTC, newling commented
Hmm with my setup in vim "\p myParam" is nicely colored and formatted. Not is VSCode?

2024-04-26 17:41 UTC, newling commented
> Also wondering what exactly is causing the tests to fail, perhaps some of the dma ops are getting removed by canonicalization as they appear like dead code? This may be why the placement of these passes is so sensitive (not saying it should be of course).

It was running canonicalization in the pipeline (CSE is fine, canonicalization results in a compilation error). I've left a TODO in the code -- we should be able to run canonicalization here AFAICT. 

I've removed the doxygen style comments

2024-04-26 20:16 UTC, nirvedhmeshram commented
> Hmm with my setup in vim "\p myParam" is nicely colored and formatted. Not is VSCode?

Nope, but frankly no strong opinion on that.

2024-04-26 20:18 UTC, nirvedhmeshram approved these changes
Thanks!

2024-04-27 00:46 UTC, merged