Remove redundant data copy of elementwise op
nod-ai/iree-amd-aie pull request #352
Opened 2024-05-15 17:36 UTC by yzhang93

- Add [upstream support](https://github.com/shark-infra/llvm-project/blob/f2d824e381755993b6e8c32f4de89192189ca9a7/mlir/lib/Dialect/Linalg/Transforms/ElementwiseOpFusion.cpp#L1864) locally to remove output dependency, since the pattern is not exposed and cannot be called directly. This pattern is added in `AMDAIEPropagateDataLayoutPass`, so that whenever we do data layout propagation it will get the desirable output for matmul-elementwise fusion. @MaheshRavishankar please let me know if it is reasonable to add it here, otherwise I'm open to move it into a separate pass or add the pattern to the cleanup pass.
- Currently, tests without vectorization compile through, but crash at `AIRToAIESchedulingUtilsPass` with vectorization. @erwei-xilinx

2024-05-15 18:13 UTC, MaheshRavishankar requested changes

2024-05-15 18:13 UTC, MaheshRavishankar commented on compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEPropagateDataLayout.cpp
> +        // If outs is sparse, leave it to the sparsifier.
Drop the sparse stuff.. unnecessary for now.

2024-05-15 18:13 UTC, MaheshRavishankar commented on compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/AMDAIEPropagateDataLayout.cpp
> +void populateElementwiseOpsFusionPatterns(RewritePatternSet &patterns) {
Rename this since we are not doing fusion. You dont need the populate method. Just add the pattern directly below.

2024-05-15 18:13 UTC, MaheshRavishankar commented on compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.cpp
> +  if (clUsePipeline == AIEPassPipeline::PadPackPipeline && numDims == 4) {
Why not use local always?

2024-05-16 21:02 UTC, yzhang93 commented
> * Currently, tests without vectorization compile through, but crash at `AIRToAIESchedulingUtilsPass` with vectorization. @erwei-xilinx

This issue is fixed by fusing the unpack op into the last forall loop based on this https://github.com/nod-ai/iree-amd-aie/pull/351. Since that PR hasn't been merged, I disable the vectorization in the elementwise test to avoid failure in ci.

2024-05-16 21:06 UTC, MaheshRavishankar approved these changes

2024-05-16 21:06 UTC, MaheshRavishankar commented on compiler/plugins/target/AMD-AIE/iree-amd-aie/Transforms/Passes.cpp
> +  if (clUsePipeline == AIEPassPipeline::PadPackPipeline && numDims == 4) {
If it doesnt its an error. For now just set local always.

2024-05-16 21:22 UTC, merged